version: '3'
services:
  redis:
    image: redis:5.0.7
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - felucca-network
    volumes:
      - redis-data:/data

networks:
  felucca-network:

volumes:
  redis-data:
